name: reassign
'on':
  workflow_dispatch:
  # schedule:
  # - cron: "*/5 * * * *"

  
jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false 
        
      - name: Install node js
        id: install_dependencies
        run: |
            npm install node.js
            
      - name: Install octokit
        id: install_octokit
        run: |
          npm install @octokit/rest@latest  

      - name: Run JavaScript script
        run: node src/reassign1809.mjs
        env:
          TOKENSS_GITHUB: ${{ secrets.TOKENSS_GITHUB }}
          
